spring:
#   application:
#     name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    pool: 6379
#  jpa:
#    show-sql: true
env:
  dev3
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8762/eureka/

girl:
  name: lili
  age: 18
